---
title: "authoritarianism"
author: "Miroslav Bergam"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse) 
```

```{r warning = FALSE}
polity <- read_excel("p5v2018 (1).xls")
```


```{r warning = FALSE}
vdem <- read.csv("V-Dem-CY-Core-v10.csv")
```

```{r}

polity <- polity %>%
  filter(country == "China") %>%
  select(country, year, polity) %>%
  filter(year >= 2000) %>%
  mutate(polity = (polity+10)/21)

#-10 to +10

vdem <- vdem %>%
  filter(country_name == "China") %>%
  select(country_name, year, v2x_polyarchy, v2x_libdem, 
         v2x_partipdem, v2x_civlib) %>%
  filter(year >= 2000) %>%
  mutate(v2x_polyarchy = v2x_polyarchy/1,
         v2x_libdem = v2x_libdem/1, 
         v2x_partipdem = v2x_partipdem/1,
         v2x_civlib = v2x_civlib/1)
  
# 0-1 for all

freedom_house <- tibble(
  `year` = c(2000:2019),
  `score` = c(13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13)
) %>%
  mutate(score = score/100)

```


```{r}

colors <- c("Polity" = "blue", "FiW" = "black", "Electoral Democracy" = "red",
            "Liberal Democracy" = "orange", "Participatory Democracy" = "maroon",
            "Civil Liberty" = "dark blue")

ggplot()+
  geom_line(data = polity, aes(x = year, y = polity, color = "Polity")) + 
  geom_line(data = freedom_house, aes(x = year, y = score, color = "FiW")) +
  geom_line(data = vdem, aes(x = year, y = v2x_polyarchy, color = "Electoral Democracy")) + 
  geom_line(data = vdem, aes(x = year, y = v2x_libdem, color = "Liberal Democracy")) + 
  geom_line(data = vdem, aes(x = year, y = v2x_partipdem, color = "Participatory Democracy")) + 
  geom_line(data = vdem, aes(x = year, y = v2x_civlib, color = "Civil Liberty")) + 
  scale_color_manual(values = colors) + 
  ylim(0,0.5) + 
  xlim(2000,2019) + 
  geom_vline(aes(xintercept = 2012), alpha = 0.5) + 
  labs(x = "Year",
       y = "Standardized Democracy Index",
       title = "Standardized V-Dem, Polity, and Freedom in the World Scores for China",
       subtitle = "China hasn't surpassed 0.4 on any of these major freedom scales in the 21st Century",
       color = "Standardized Rating System") + 
  annotate("text", x = 2016, y = 0.4, label = "Xi Jinping assumes office", color = "#3A3B3C", size = 3)

```




